/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MovementType = { 'out' : null } |
  { 'stockIn' : null };
export interface Product {
  'id' : bigint,
  'sku' : string,
  'name' : string,
  'createdAt' : bigint,
  'unit' : string,
  'sellingPrice' : number,
  'category' : string,
  'reorderLevel' : bigint,
  'currentStock' : bigint,
  'costPrice' : number,
}
export interface ReportResult {
  'productSummaries' : Array<[bigint, ReportSummary]>,
  'overallSummary' : ReportSummary,
  'movements' : Array<StockMovement>,
}
export interface ReportSummary {
  'totalIn' : bigint,
  'totalOut' : bigint,
  'netChange' : bigint,
}
export interface StockMovement {
  'id' : bigint,
  'note' : string,
  'productId' : bigint,
  'movementType' : MovementType,
  'timestamp' : bigint,
  'quantity' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<
    [string, string, string, string, number, number, bigint, bigint],
    bigint
  >,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLowStockProducts' : ActorMethod<[], Array<Product>>,
  'getMovementsForProduct' : ActorMethod<[bigint], Array<StockMovement>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getReport' : ActorMethod<[bigint, bigint], ReportResult>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordStockMovement' : ActorMethod<
    [bigint, MovementType, bigint, string, bigint],
    bigint
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, string, string, number, number, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];