/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'unit' : IDL.Text,
  'sellingPrice' : IDL.Float64,
  'category' : IDL.Text,
  'reorderLevel' : IDL.Nat,
  'currentStock' : IDL.Nat,
  'costPrice' : IDL.Float64,
});
export const MovementType = IDL.Variant({
  'out' : IDL.Null,
  'stockIn' : IDL.Null,
});
export const StockMovement = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'productId' : IDL.Nat,
  'movementType' : MovementType,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
});
export const ReportSummary = IDL.Record({
  'totalIn' : IDL.Nat,
  'totalOut' : IDL.Nat,
  'netChange' : IDL.Int,
});
export const ReportResult = IDL.Record({
  'productSummaries' : IDL.Vec(IDL.Tuple(IDL.Nat, ReportSummary)),
  'overallSummary' : ReportSummary,
  'movements' : IDL.Vec(StockMovement),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Int,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMovementsForProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(StockMovement)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getReport' : IDL.Func([IDL.Int, IDL.Int], [ReportResult], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordStockMovement' : IDL.Func(
      [IDL.Nat, MovementType, IDL.Nat, IDL.Text, IDL.Int],
      [IDL.Nat],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'unit' : IDL.Text,
    'sellingPrice' : IDL.Float64,
    'category' : IDL.Text,
    'reorderLevel' : IDL.Nat,
    'currentStock' : IDL.Nat,
    'costPrice' : IDL.Float64,
  });
  const MovementType = IDL.Variant({ 'out' : IDL.Null, 'stockIn' : IDL.Null });
  const StockMovement = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'productId' : IDL.Nat,
    'movementType' : MovementType,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
  });
  const ReportSummary = IDL.Record({
    'totalIn' : IDL.Nat,
    'totalOut' : IDL.Nat,
    'netChange' : IDL.Int,
  });
  const ReportResult = IDL.Record({
    'productSummaries' : IDL.Vec(IDL.Tuple(IDL.Nat, ReportSummary)),
    'overallSummary' : ReportSummary,
    'movements' : IDL.Vec(StockMovement),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Int,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLowStockProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMovementsForProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(StockMovement)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getReport' : IDL.Func([IDL.Int, IDL.Int], [ReportResult], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordStockMovement' : IDL.Func(
        [IDL.Nat, MovementType, IDL.Nat, IDL.Text, IDL.Int],
        [IDL.Nat],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };